extern "C" void _ZN7android12MetaDataBase13writeToParcelERNS_6ParcelE () {}
extern "C" void _ZN7android8MetaData16createFromParcelERKNS_6ParcelE () {}
extern "C" void _ZN7android12MetaDataBase16updateFromParcelERKNS_6ParcelE () {}
extern "C" void _ZN7android8AMessage10FromParcelERKNS_6ParcelEj () {}
extern "C" void _ZNK7android8AMessage13writeToParcelEPNS_6ParcelE () {}
extern "C" void _ZN7android7AString10FromParcelERKNS_6ParcelE () {}
extern "C" void _ZNK7android7AString13writeToParcelEPNS_6ParcelE () {}
extern "C" void __exidx_end () {}
extern "C" void __exidx_start () {}
extern "C" void img_common_get_frame_fmt () {}
extern "C" void _ZN7android9nameForFdEi () {}
extern "C" void _ZN7android13MakeUserAgentEv () {}
extern "C" void _ZN7android14uriDebugStringERKNS_7AStringEb () {}
